from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from cooking import views
from cooking.views import RecipeListAPIView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage,name="homepage"),
    path('user_login/',views.user_login,name="user_login"),
    path('user_register_code/',views.user_register_code,name="user_register_code"),
    path('user_login_validation/',views.user_login_validation,name="user_login_validation"),
    path('unified_login_validation/',views.unified_login_validation,name="unified_login_validation"),
    path('user_dashboard/',views.user_dashboard,name="user_dashboard"),
    path('admin_login/',views.admin_login,name="admin_login"),
    path('admin_login_validation/',views.admin_login_validation,name="admin_login_validation"),
    path('admin_dashboard/',views.admin_dashboard,name="admin_dashboard"),
    path('logoutview/',views.logoutview,name="logoutview"),
    path('view_all_user/',views.view_all_user,name="view_all_user"),
    path('delete_user/<int:id>/',views.delete_user,name="delete_user"),
    path('delete_chef/<int:id>/',views.delete_chef,name="delete_chef"),
    path('chef_login/',views.chef_login,name="chef_login"),
    path('chef_register_code/',views.chef_register_code,name="chef_register_code"),
    path('user_profile/',views.user_profile,name="user_profile"),
    path('update_profile_code/',views.update_profile_code,name="update_profile_code"),
    path('chef_login_validation/',views.chef_login_validation,name="chef_login_validation"),
    path('chef_dashboard/',views.chef_dashboard,name="chef_dashboard"),
    path('upload_recipe/',views.upload_recipe,name="upload_recipe"),
    path('upload_recipe_code/',views.upload_recipe_code,name="upload_recipe_code"),
    path('recipe_list/<int:id>/', views.recipe_list, name='recipe_list'),
    path('recipe_gallery/',views.recipe_gallery,name="recipe_gallery"),
    path('recipe_detail/<int:recipe_id>/',views.recipe_detail,name="recipe_detail"),
    path('chef_recipe_detail/<int:recipe_id>/',views.chef_recipe_detail,name="chef_recipe_detail"),
    path('my_recipe/',views.my_recipe,name="my_recipe"),
    path('delete_recipe/<int:id>/',views.delete_recipe,name="delete_recipe"),
    path('search_recipe/',views.search_recipe,name="search_recipe"),
    path('view_all_chef/',views.view_all_chef,name="view_all_chef"),
    path('view_recipe_admin/',views.view_recipe_admin,name="view_recipe_admin"),
    path('save/<int:recipe_id>/',views.save_recipe, name='save_recipe'),
    path('saved-recipes/', views.saved_recipes, name='saved_recipes'),
    path('recommend/<int:recipe_id>/', views.add_recommendation, name='add_recommendation'),
    path('recipe/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('my-recipe-reviews/', views.my_recipe_reviews, name='my_recipe_reviews'),
    path('chef_upload_recipe/',views.chef_upload_recipe,name="chef_upload_recipe"),
    path('chef_profile/',views.chef_profile,name="chef_profile"),
    path('upload_recipe_code_chef/',views.upload_recipe_code_chef,name="upload_recipe_code_chef"),
    path('delete_recipe_admin/<int:id>/',views.delete_recipe_admin,name="delete_recipe_admin"),
    path('chef_profile_edit/',views.chef_profile_edit,name="chef_profile_edit"),
    path('chef_profile_edit/',views.chef_profile_edit,name="chef_profile_edit"),
    path('chef_list/',views.chef_list,name="chef_list"),
    path('book-chef/<int:chef_id>/', views.book_chef, name='book_chef'),
    path('book_chef_code/',views.book_chef_code,name="book_chef_code"),
    path('user_booking/',views.user_booking,name="user_booking"),
    path('email/',views.email,name="email"),
    path('send_email/',views.send_email,name="send_email"),
    path('chef_booking/',views.chef_booking,name="chef_booking"),
    path('approvrent/<int:id>/',views.approvrent,name="approvrent"),
    path('disapprovrent/<int:id>/',views.disapprovrent,name="disapprovrent"),
    path('view_all_booking/',views.view_all_booking,name="view_all_booking"),
    path('approvrecipe/<int:id>/',views.approvrecipe,name="approvrecipe"),
    path('disapprovrecipe/<int:id>/',views.disapprovrecipe,name="disapprovrecipe"),
    path('forgot_password_user/',views.forgot_password_user,name="forgot_password_user"),
    path('forgot_password_user_code/',views.forgot_password_user_code,name="forgot_password_user_code"),
    path('search_recipe_ingridents/',views.search_recipe_ingridents,name="search_recipe_ingridents"),
    path('remove_saved_recipe/<int:id>/',views.remove_saved_recipe,name="remove_saved_recipe"),
    path('forgot_password_chef/',views.forgot_password_chef,name="forgot_password_chef"),
    path('follow_user/',views.follow_user,name="follow_user"),
    path('follow/profile/<int:recipe_id>/', views.follow_page, name='follow_page'),
    path('follow/toggle/<int:chef_id>/', views.toggle_follow_chef, name='toggle_follow_chef'),
    path('follow/toggle-email/<str:target_email>/', views.toggle_follow_by_email, name='toggle_follow_by_email'),
    path('following_page/',views.following_page,name="following_page"),
    path('search_recipe_duration/',views.search_recipe_duration,name="search_recipe_duration"),
    path('forgot_password_chef_code/',views.forgot_password_chef_code,name="forgot_password_chef_code"),
    path('subscription/',views.subscription,name="subscription"),
    path('recipe_detail/<int:recipe_id>/',views.recipe_detail,name="recipe_detail"),   
    path('edit_recipe/<int:recipe_id>/',           views.edit_recipe,           name="edit_recipe"),
    path('edit_recipe_code/<int:recipe_id>/',      views.edit_recipe_code,      name="edit_recipe_code"),
    path('chef_edit_recipe/<int:recipe_id>/',      views.chef_edit_recipe,      name="chef_edit_recipe"),
    path('chef_edit_recipe_code/<int:recipe_id>/', views.chef_edit_recipe_code, name="chef_edit_recipe_code"),
    path('chef_recipe_gallery/',                   views.chef_recipe_gallery,   name="chef_recipe_gallery"),
    path('chef_delete_recipe/<int:id>/',           views.chef_delete_recipe,    name="chef_delete_recipe"),
    path('recipe/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('warning/',views.warning,name="warning"),
    path('delete_review_admin/<int:id>/', views.delete_review_admin, name='delete_review_admin'),
    path('admin_recipe_detail/<int:recipe_id>/', views.admin_recipe_detail, name="admin_recipe_detail"),
    path('admin_edit_recipe_save/<int:recipe_id>/', views.admin_edit_recipe_save, name='admin_edit_recipe_save'),
    path('delete_user_account/', views.delete_user_account_page, name='delete_user_account_page'),
    path('delete_user_account/confirm/', views.delete_user_account_confirm, name='delete_user_account_confirm'),
    path('delete_chef_account/', views.delete_chef_account_page, name='delete_chef_account_page'),
    path('delete_chef_account/confirm/', views.delete_chef_account_confirm, name='delete_chef_account_confirm'),
    path('api/recipes/', RecipeListAPIView.as_view(), name='recipe-list'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)