# Generated by Django 3.2.25 on 2026-03-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('contact', models.TextField(max_length=255)),
                ('password', models.TextField(max_length=255)),
            ],
        ),
    ]
