# Generated by Django 3.2.25 on 2026-03-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.TextField(max_length=255)),
                ('admin_password', models.TextField(max_length=50)),
            ],
        ),
    ]
