# Generated by Django 3.2.25 on 2026-03-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_image', models.ImageField(upload_to='recipes/')),
                ('recipe_video', models.ImageField(upload_to='recipes_video/')),
                ('category', models.CharField(max_length=100)),
                ('cooking_time', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('description', models.CharField(max_length=200)),
                ('steps', models.TextField()),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
            ],
        ),
    ]
