# Generated by Django 3.2.25 on 2026-03-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=255)),
                ('recipe', models.TextField(max_length=255)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
