# Generated by Django 3.2.25 on 2026-03-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0005_auto_20260323_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedRecipe',
        ),
    ]
