# Generated by Django 3.2.25 on 2026-03-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0006_delete_savedrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking.user')),
            ],
            options={
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
