# Generated by Django 3.2.25 on 2026-03-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0008_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='chef_image',
            field=models.FileField(default=1, upload_to='chef_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chef',
            name='experince',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
