# Generated by Django 3.2.25 on 2026-03-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0009_auto_20260323_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_email', models.EmailField(max_length=254)),
                ('user_email', models.EmailField(max_length=254)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=255)),
                ('number_of_people', models.IntegerField()),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('chef_email', 'event_date')},
            },
        ),
    ]
