# Generated by Django 3.2.25 on 2026-03-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0010_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='chef_name',
            field=models.CharField(default='H', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user_name',
            field=models.CharField(default='h', max_length=255),
            preserve_default=False,
        ),
    ]
