# Generated by Django 3.2.25 on 2026-03-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0011_auto_20260325_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.TextField(default='Pending'),
        ),
    ]
