# Generated by Django 3.2.25 on 2026-03-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0013_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.TextField(default='Pending'),
        ),
    ]
