# Generated by Django 3.2.25 on 2026-04-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0015_auto_20260401_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='cooking.user'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
