# Generated by Django 3.2.25 on 2026-04-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0016_auto_20260401_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
    ]
