# Generated by Django 3.2.25 on 2026-04-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0017_auto_20260401_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_video',
            field=models.FileField(blank=True, null=True, upload_to='recipes_video/'),
        ),
    ]
