# Generated by Django 3.2.25 on 2026-04-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0019_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, default='recipe_images/default.png', null=True, upload_to='recipe_images/'),
        ),
    ]
